# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/Gagnon/Documents/4th Year/CPSC436D/Stealthy_Sam/team05game"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/Gagnon/Documents/4th Year/CPSC436D/Stealthy_Sam/team05game"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/Gagnon/Documents/4th Year/CPSC436D/Stealthy_Sam/team05game/CMakeFiles" "/Users/Gagnon/Documents/4th Year/CPSC436D/Stealthy_Sam/team05game/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/Gagnon/Documents/4th Year/CPSC436D/Stealthy_Sam/team05game/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 436d

# Build rule for target.
436d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 436d
.PHONY : 436d

# fast build rule for target.
436d/fast:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/build
.PHONY : 436d/fast

src/CollisionSystem.o: src/CollisionSystem.cpp.o

.PHONY : src/CollisionSystem.o

# target to build an object file
src/CollisionSystem.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/CollisionSystem.cpp.o
.PHONY : src/CollisionSystem.cpp.o

src/CollisionSystem.i: src/CollisionSystem.cpp.i

.PHONY : src/CollisionSystem.i

# target to preprocess a source file
src/CollisionSystem.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/CollisionSystem.cpp.i
.PHONY : src/CollisionSystem.cpp.i

src/CollisionSystem.s: src/CollisionSystem.cpp.s

.PHONY : src/CollisionSystem.s

# target to generate assembly for a file
src/CollisionSystem.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/CollisionSystem.cpp.s
.PHONY : src/CollisionSystem.cpp.s

src/Components/CollisionCmp.o: src/Components/CollisionCmp.cpp.o

.PHONY : src/Components/CollisionCmp.o

# target to build an object file
src/Components/CollisionCmp.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/CollisionCmp.cpp.o
.PHONY : src/Components/CollisionCmp.cpp.o

src/Components/CollisionCmp.i: src/Components/CollisionCmp.cpp.i

.PHONY : src/Components/CollisionCmp.i

# target to preprocess a source file
src/Components/CollisionCmp.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/CollisionCmp.cpp.i
.PHONY : src/Components/CollisionCmp.cpp.i

src/Components/CollisionCmp.s: src/Components/CollisionCmp.cpp.s

.PHONY : src/Components/CollisionCmp.s

# target to generate assembly for a file
src/Components/CollisionCmp.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/CollisionCmp.cpp.s
.PHONY : src/Components/CollisionCmp.cpp.s

src/Components/DrawCmp.o: src/Components/DrawCmp.cpp.o

.PHONY : src/Components/DrawCmp.o

# target to build an object file
src/Components/DrawCmp.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/DrawCmp.cpp.o
.PHONY : src/Components/DrawCmp.cpp.o

src/Components/DrawCmp.i: src/Components/DrawCmp.cpp.i

.PHONY : src/Components/DrawCmp.i

# target to preprocess a source file
src/Components/DrawCmp.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/DrawCmp.cpp.i
.PHONY : src/Components/DrawCmp.cpp.i

src/Components/DrawCmp.s: src/Components/DrawCmp.cpp.s

.PHONY : src/Components/DrawCmp.s

# target to generate assembly for a file
src/Components/DrawCmp.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/DrawCmp.cpp.s
.PHONY : src/Components/DrawCmp.cpp.s

src/Components/EnemyCmp.o: src/Components/EnemyCmp.cpp.o

.PHONY : src/Components/EnemyCmp.o

# target to build an object file
src/Components/EnemyCmp.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/EnemyCmp.cpp.o
.PHONY : src/Components/EnemyCmp.cpp.o

src/Components/EnemyCmp.i: src/Components/EnemyCmp.cpp.i

.PHONY : src/Components/EnemyCmp.i

# target to preprocess a source file
src/Components/EnemyCmp.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/EnemyCmp.cpp.i
.PHONY : src/Components/EnemyCmp.cpp.i

src/Components/EnemyCmp.s: src/Components/EnemyCmp.cpp.s

.PHONY : src/Components/EnemyCmp.s

# target to generate assembly for a file
src/Components/EnemyCmp.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/EnemyCmp.cpp.s
.PHONY : src/Components/EnemyCmp.cpp.s

src/Components/GameStateCmp.o: src/Components/GameStateCmp.cpp.o

.PHONY : src/Components/GameStateCmp.o

# target to build an object file
src/Components/GameStateCmp.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/GameStateCmp.cpp.o
.PHONY : src/Components/GameStateCmp.cpp.o

src/Components/GameStateCmp.i: src/Components/GameStateCmp.cpp.i

.PHONY : src/Components/GameStateCmp.i

# target to preprocess a source file
src/Components/GameStateCmp.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/GameStateCmp.cpp.i
.PHONY : src/Components/GameStateCmp.cpp.i

src/Components/GameStateCmp.s: src/Components/GameStateCmp.cpp.s

.PHONY : src/Components/GameStateCmp.s

# target to generate assembly for a file
src/Components/GameStateCmp.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/GameStateCmp.cpp.s
.PHONY : src/Components/GameStateCmp.cpp.s

src/Components/InputCmp.o: src/Components/InputCmp.cpp.o

.PHONY : src/Components/InputCmp.o

# target to build an object file
src/Components/InputCmp.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/InputCmp.cpp.o
.PHONY : src/Components/InputCmp.cpp.o

src/Components/InputCmp.i: src/Components/InputCmp.cpp.i

.PHONY : src/Components/InputCmp.i

# target to preprocess a source file
src/Components/InputCmp.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/InputCmp.cpp.i
.PHONY : src/Components/InputCmp.cpp.i

src/Components/InputCmp.s: src/Components/InputCmp.cpp.s

.PHONY : src/Components/InputCmp.s

# target to generate assembly for a file
src/Components/InputCmp.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/InputCmp.cpp.s
.PHONY : src/Components/InputCmp.cpp.s

src/Components/ItemCmp.o: src/Components/ItemCmp.cpp.o

.PHONY : src/Components/ItemCmp.o

# target to build an object file
src/Components/ItemCmp.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/ItemCmp.cpp.o
.PHONY : src/Components/ItemCmp.cpp.o

src/Components/ItemCmp.i: src/Components/ItemCmp.cpp.i

.PHONY : src/Components/ItemCmp.i

# target to preprocess a source file
src/Components/ItemCmp.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/ItemCmp.cpp.i
.PHONY : src/Components/ItemCmp.cpp.i

src/Components/ItemCmp.s: src/Components/ItemCmp.cpp.s

.PHONY : src/Components/ItemCmp.s

# target to generate assembly for a file
src/Components/ItemCmp.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/ItemCmp.cpp.s
.PHONY : src/Components/ItemCmp.cpp.s

src/Components/MovementCmp.o: src/Components/MovementCmp.cpp.o

.PHONY : src/Components/MovementCmp.o

# target to build an object file
src/Components/MovementCmp.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/MovementCmp.cpp.o
.PHONY : src/Components/MovementCmp.cpp.o

src/Components/MovementCmp.i: src/Components/MovementCmp.cpp.i

.PHONY : src/Components/MovementCmp.i

# target to preprocess a source file
src/Components/MovementCmp.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/MovementCmp.cpp.i
.PHONY : src/Components/MovementCmp.cpp.i

src/Components/MovementCmp.s: src/Components/MovementCmp.cpp.s

.PHONY : src/Components/MovementCmp.s

# target to generate assembly for a file
src/Components/MovementCmp.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/MovementCmp.cpp.s
.PHONY : src/Components/MovementCmp.cpp.s

src/Components/ParticleCmp.o: src/Components/ParticleCmp.cpp.o

.PHONY : src/Components/ParticleCmp.o

# target to build an object file
src/Components/ParticleCmp.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/ParticleCmp.cpp.o
.PHONY : src/Components/ParticleCmp.cpp.o

src/Components/ParticleCmp.i: src/Components/ParticleCmp.cpp.i

.PHONY : src/Components/ParticleCmp.i

# target to preprocess a source file
src/Components/ParticleCmp.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/ParticleCmp.cpp.i
.PHONY : src/Components/ParticleCmp.cpp.i

src/Components/ParticleCmp.s: src/Components/ParticleCmp.cpp.s

.PHONY : src/Components/ParticleCmp.s

# target to generate assembly for a file
src/Components/ParticleCmp.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/ParticleCmp.cpp.s
.PHONY : src/Components/ParticleCmp.cpp.s

src/Components/TransformCmp.o: src/Components/TransformCmp.cpp.o

.PHONY : src/Components/TransformCmp.o

# target to build an object file
src/Components/TransformCmp.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/TransformCmp.cpp.o
.PHONY : src/Components/TransformCmp.cpp.o

src/Components/TransformCmp.i: src/Components/TransformCmp.cpp.i

.PHONY : src/Components/TransformCmp.i

# target to preprocess a source file
src/Components/TransformCmp.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/TransformCmp.cpp.i
.PHONY : src/Components/TransformCmp.cpp.i

src/Components/TransformCmp.s: src/Components/TransformCmp.cpp.s

.PHONY : src/Components/TransformCmp.s

# target to generate assembly for a file
src/Components/TransformCmp.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Components/TransformCmp.cpp.s
.PHONY : src/Components/TransformCmp.cpp.s

src/DecisionNode.o: src/DecisionNode.cpp.o

.PHONY : src/DecisionNode.o

# target to build an object file
src/DecisionNode.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/DecisionNode.cpp.o
.PHONY : src/DecisionNode.cpp.o

src/DecisionNode.i: src/DecisionNode.cpp.i

.PHONY : src/DecisionNode.i

# target to preprocess a source file
src/DecisionNode.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/DecisionNode.cpp.i
.PHONY : src/DecisionNode.cpp.i

src/DecisionNode.s: src/DecisionNode.cpp.s

.PHONY : src/DecisionNode.s

# target to generate assembly for a file
src/DecisionNode.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/DecisionNode.cpp.s
.PHONY : src/DecisionNode.cpp.s

src/DrawSystem.o: src/DrawSystem.cpp.o

.PHONY : src/DrawSystem.o

# target to build an object file
src/DrawSystem.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/DrawSystem.cpp.o
.PHONY : src/DrawSystem.cpp.o

src/DrawSystem.i: src/DrawSystem.cpp.i

.PHONY : src/DrawSystem.i

# target to preprocess a source file
src/DrawSystem.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/DrawSystem.cpp.i
.PHONY : src/DrawSystem.cpp.i

src/DrawSystem.s: src/DrawSystem.cpp.s

.PHONY : src/DrawSystem.s

# target to generate assembly for a file
src/DrawSystem.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/DrawSystem.cpp.s
.PHONY : src/DrawSystem.cpp.s

src/EnemyCone.o: src/EnemyCone.cpp.o

.PHONY : src/EnemyCone.o

# target to build an object file
src/EnemyCone.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/EnemyCone.cpp.o
.PHONY : src/EnemyCone.cpp.o

src/EnemyCone.i: src/EnemyCone.cpp.i

.PHONY : src/EnemyCone.i

# target to preprocess a source file
src/EnemyCone.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/EnemyCone.cpp.i
.PHONY : src/EnemyCone.cpp.i

src/EnemyCone.s: src/EnemyCone.cpp.s

.PHONY : src/EnemyCone.s

# target to generate assembly for a file
src/EnemyCone.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/EnemyCone.cpp.s
.PHONY : src/EnemyCone.cpp.s

src/EnemySystem.o: src/EnemySystem.cpp.o

.PHONY : src/EnemySystem.o

# target to build an object file
src/EnemySystem.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/EnemySystem.cpp.o
.PHONY : src/EnemySystem.cpp.o

src/EnemySystem.i: src/EnemySystem.cpp.i

.PHONY : src/EnemySystem.i

# target to preprocess a source file
src/EnemySystem.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/EnemySystem.cpp.i
.PHONY : src/EnemySystem.cpp.i

src/EnemySystem.s: src/EnemySystem.cpp.s

.PHONY : src/EnemySystem.s

# target to generate assembly for a file
src/EnemySystem.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/EnemySystem.cpp.s
.PHONY : src/EnemySystem.cpp.s

src/EntityGenerator.o: src/EntityGenerator.cpp.o

.PHONY : src/EntityGenerator.o

# target to build an object file
src/EntityGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/EntityGenerator.cpp.o
.PHONY : src/EntityGenerator.cpp.o

src/EntityGenerator.i: src/EntityGenerator.cpp.i

.PHONY : src/EntityGenerator.i

# target to preprocess a source file
src/EntityGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/EntityGenerator.cpp.i
.PHONY : src/EntityGenerator.cpp.i

src/EntityGenerator.s: src/EntityGenerator.cpp.s

.PHONY : src/EntityGenerator.s

# target to generate assembly for a file
src/EntityGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/EntityGenerator.cpp.s
.PHONY : src/EntityGenerator.cpp.s

src/InputSystem.o: src/InputSystem.cpp.o

.PHONY : src/InputSystem.o

# target to build an object file
src/InputSystem.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/InputSystem.cpp.o
.PHONY : src/InputSystem.cpp.o

src/InputSystem.i: src/InputSystem.cpp.i

.PHONY : src/InputSystem.i

# target to preprocess a source file
src/InputSystem.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/InputSystem.cpp.i
.PHONY : src/InputSystem.cpp.i

src/InputSystem.s: src/InputSystem.cpp.s

.PHONY : src/InputSystem.s

# target to generate assembly for a file
src/InputSystem.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/InputSystem.cpp.s
.PHONY : src/InputSystem.cpp.s

src/LightSystem.o: src/LightSystem.cpp.o

.PHONY : src/LightSystem.o

# target to build an object file
src/LightSystem.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/LightSystem.cpp.o
.PHONY : src/LightSystem.cpp.o

src/LightSystem.i: src/LightSystem.cpp.i

.PHONY : src/LightSystem.i

# target to preprocess a source file
src/LightSystem.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/LightSystem.cpp.i
.PHONY : src/LightSystem.cpp.i

src/LightSystem.s: src/LightSystem.cpp.s

.PHONY : src/LightSystem.s

# target to generate assembly for a file
src/LightSystem.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/LightSystem.cpp.s
.PHONY : src/LightSystem.cpp.s

src/MissileSystem.o: src/MissileSystem.cpp.o

.PHONY : src/MissileSystem.o

# target to build an object file
src/MissileSystem.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/MissileSystem.cpp.o
.PHONY : src/MissileSystem.cpp.o

src/MissileSystem.i: src/MissileSystem.cpp.i

.PHONY : src/MissileSystem.i

# target to preprocess a source file
src/MissileSystem.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/MissileSystem.cpp.i
.PHONY : src/MissileSystem.cpp.i

src/MissileSystem.s: src/MissileSystem.cpp.s

.PHONY : src/MissileSystem.s

# target to generate assembly for a file
src/MissileSystem.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/MissileSystem.cpp.s
.PHONY : src/MissileSystem.cpp.s

src/MovementSystem.o: src/MovementSystem.cpp.o

.PHONY : src/MovementSystem.o

# target to build an object file
src/MovementSystem.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/MovementSystem.cpp.o
.PHONY : src/MovementSystem.cpp.o

src/MovementSystem.i: src/MovementSystem.cpp.i

.PHONY : src/MovementSystem.i

# target to preprocess a source file
src/MovementSystem.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/MovementSystem.cpp.i
.PHONY : src/MovementSystem.cpp.i

src/MovementSystem.s: src/MovementSystem.cpp.s

.PHONY : src/MovementSystem.s

# target to generate assembly for a file
src/MovementSystem.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/MovementSystem.cpp.s
.PHONY : src/MovementSystem.cpp.s

src/ObjectManager.o: src/ObjectManager.cpp.o

.PHONY : src/ObjectManager.o

# target to build an object file
src/ObjectManager.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/ObjectManager.cpp.o
.PHONY : src/ObjectManager.cpp.o

src/ObjectManager.i: src/ObjectManager.cpp.i

.PHONY : src/ObjectManager.i

# target to preprocess a source file
src/ObjectManager.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/ObjectManager.cpp.i
.PHONY : src/ObjectManager.cpp.i

src/ObjectManager.s: src/ObjectManager.cpp.s

.PHONY : src/ObjectManager.s

# target to generate assembly for a file
src/ObjectManager.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/ObjectManager.cpp.s
.PHONY : src/ObjectManager.cpp.s

src/ParticleSystem.o: src/ParticleSystem.cpp.o

.PHONY : src/ParticleSystem.o

# target to build an object file
src/ParticleSystem.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/ParticleSystem.cpp.o
.PHONY : src/ParticleSystem.cpp.o

src/ParticleSystem.i: src/ParticleSystem.cpp.i

.PHONY : src/ParticleSystem.i

# target to preprocess a source file
src/ParticleSystem.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/ParticleSystem.cpp.i
.PHONY : src/ParticleSystem.cpp.i

src/ParticleSystem.s: src/ParticleSystem.cpp.s

.PHONY : src/ParticleSystem.s

# target to generate assembly for a file
src/ParticleSystem.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/ParticleSystem.cpp.s
.PHONY : src/ParticleSystem.cpp.s

src/SoundManager.o: src/SoundManager.cpp.o

.PHONY : src/SoundManager.o

# target to build an object file
src/SoundManager.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/SoundManager.cpp.o
.PHONY : src/SoundManager.cpp.o

src/SoundManager.i: src/SoundManager.cpp.i

.PHONY : src/SoundManager.i

# target to preprocess a source file
src/SoundManager.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/SoundManager.cpp.i
.PHONY : src/SoundManager.cpp.i

src/SoundManager.s: src/SoundManager.cpp.s

.PHONY : src/SoundManager.s

# target to generate assembly for a file
src/SoundManager.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/SoundManager.cpp.s
.PHONY : src/SoundManager.cpp.s

src/Strategies/BossStrategy.o: src/Strategies/BossStrategy.cpp.o

.PHONY : src/Strategies/BossStrategy.o

# target to build an object file
src/Strategies/BossStrategy.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Strategies/BossStrategy.cpp.o
.PHONY : src/Strategies/BossStrategy.cpp.o

src/Strategies/BossStrategy.i: src/Strategies/BossStrategy.cpp.i

.PHONY : src/Strategies/BossStrategy.i

# target to preprocess a source file
src/Strategies/BossStrategy.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Strategies/BossStrategy.cpp.i
.PHONY : src/Strategies/BossStrategy.cpp.i

src/Strategies/BossStrategy.s: src/Strategies/BossStrategy.cpp.s

.PHONY : src/Strategies/BossStrategy.s

# target to generate assembly for a file
src/Strategies/BossStrategy.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/Strategies/BossStrategy.cpp.s
.PHONY : src/Strategies/BossStrategy.cpp.s

src/TextSystem.o: src/TextSystem.cpp.o

.PHONY : src/TextSystem.o

# target to build an object file
src/TextSystem.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/TextSystem.cpp.o
.PHONY : src/TextSystem.cpp.o

src/TextSystem.i: src/TextSystem.cpp.i

.PHONY : src/TextSystem.i

# target to preprocess a source file
src/TextSystem.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/TextSystem.cpp.i
.PHONY : src/TextSystem.cpp.i

src/TextSystem.s: src/TextSystem.cpp.s

.PHONY : src/TextSystem.s

# target to generate assembly for a file
src/TextSystem.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/TextSystem.cpp.s
.PHONY : src/TextSystem.cpp.s

src/common.o: src/common.cpp.o

.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/light.o: src/light.cpp.o

.PHONY : src/light.o

# target to build an object file
src/light.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/light.cpp.o
.PHONY : src/light.cpp.o

src/light.i: src/light.cpp.i

.PHONY : src/light.i

# target to preprocess a source file
src/light.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/light.cpp.i
.PHONY : src/light.cpp.i

src/light.s: src/light.cpp.s

.PHONY : src/light.s

# target to generate assembly for a file
src/light.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/light.cpp.s
.PHONY : src/light.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/text.o: src/text.cpp.o

.PHONY : src/text.o

# target to build an object file
src/text.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/text.cpp.o
.PHONY : src/text.cpp.o

src/text.i: src/text.cpp.i

.PHONY : src/text.i

# target to preprocess a source file
src/text.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/text.cpp.i
.PHONY : src/text.cpp.i

src/text.s: src/text.cpp.s

.PHONY : src/text.s

# target to generate assembly for a file
src/text.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/text.cpp.s
.PHONY : src/text.cpp.s

src/world.o: src/world.cpp.o

.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i

.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s

.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) -f CMakeFiles/436d.dir/build.make CMakeFiles/436d.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... 436d"
	@echo "... src/CollisionSystem.o"
	@echo "... src/CollisionSystem.i"
	@echo "... src/CollisionSystem.s"
	@echo "... src/Components/CollisionCmp.o"
	@echo "... src/Components/CollisionCmp.i"
	@echo "... src/Components/CollisionCmp.s"
	@echo "... src/Components/DrawCmp.o"
	@echo "... src/Components/DrawCmp.i"
	@echo "... src/Components/DrawCmp.s"
	@echo "... src/Components/EnemyCmp.o"
	@echo "... src/Components/EnemyCmp.i"
	@echo "... src/Components/EnemyCmp.s"
	@echo "... src/Components/GameStateCmp.o"
	@echo "... src/Components/GameStateCmp.i"
	@echo "... src/Components/GameStateCmp.s"
	@echo "... src/Components/InputCmp.o"
	@echo "... src/Components/InputCmp.i"
	@echo "... src/Components/InputCmp.s"
	@echo "... src/Components/ItemCmp.o"
	@echo "... src/Components/ItemCmp.i"
	@echo "... src/Components/ItemCmp.s"
	@echo "... src/Components/MovementCmp.o"
	@echo "... src/Components/MovementCmp.i"
	@echo "... src/Components/MovementCmp.s"
	@echo "... src/Components/ParticleCmp.o"
	@echo "... src/Components/ParticleCmp.i"
	@echo "... src/Components/ParticleCmp.s"
	@echo "... src/Components/TransformCmp.o"
	@echo "... src/Components/TransformCmp.i"
	@echo "... src/Components/TransformCmp.s"
	@echo "... src/DecisionNode.o"
	@echo "... src/DecisionNode.i"
	@echo "... src/DecisionNode.s"
	@echo "... src/DrawSystem.o"
	@echo "... src/DrawSystem.i"
	@echo "... src/DrawSystem.s"
	@echo "... src/EnemyCone.o"
	@echo "... src/EnemyCone.i"
	@echo "... src/EnemyCone.s"
	@echo "... src/EnemySystem.o"
	@echo "... src/EnemySystem.i"
	@echo "... src/EnemySystem.s"
	@echo "... src/EntityGenerator.o"
	@echo "... src/EntityGenerator.i"
	@echo "... src/EntityGenerator.s"
	@echo "... src/InputSystem.o"
	@echo "... src/InputSystem.i"
	@echo "... src/InputSystem.s"
	@echo "... src/LightSystem.o"
	@echo "... src/LightSystem.i"
	@echo "... src/LightSystem.s"
	@echo "... src/MissileSystem.o"
	@echo "... src/MissileSystem.i"
	@echo "... src/MissileSystem.s"
	@echo "... src/MovementSystem.o"
	@echo "... src/MovementSystem.i"
	@echo "... src/MovementSystem.s"
	@echo "... src/ObjectManager.o"
	@echo "... src/ObjectManager.i"
	@echo "... src/ObjectManager.s"
	@echo "... src/ParticleSystem.o"
	@echo "... src/ParticleSystem.i"
	@echo "... src/ParticleSystem.s"
	@echo "... src/SoundManager.o"
	@echo "... src/SoundManager.i"
	@echo "... src/SoundManager.s"
	@echo "... src/Strategies/BossStrategy.o"
	@echo "... src/Strategies/BossStrategy.i"
	@echo "... src/Strategies/BossStrategy.s"
	@echo "... src/TextSystem.o"
	@echo "... src/TextSystem.i"
	@echo "... src/TextSystem.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/light.o"
	@echo "... src/light.i"
	@echo "... src/light.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/text.o"
	@echo "... src/text.i"
	@echo "... src/text.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

